# lisa.toml
# to sync with lisa run 'mona sync'
# supported types: string, int, float, bool, inline table (json)

string_param = "hi"
float_param = 0.0
bool_param = true

json_param = {
  "key": "value"
}

# nested tables resolve to nested json
# the code below is the same as
# nested_table  = {
#   shallow_level = 1, 
#   deeper_nest = {
#     deep_level = 2
#   }
# }
# are the same things
[nested_table]
shallow_level = "top"
[deeper_nest]
deep_level = "deep"
